[package]
name = "blocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blocks_lib = {path = "./blocks_lib", version="0.1.0"}